FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["ZeladoriaUrbana.API.csproj", "./"]
RUN dotnet restore "ZeladoriaUrbana.API.csproj"

COPY . .
RUN dotnet publish "ZeladoriaUrbana.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ZeladoriaUrbana.API.dll"]